#!/bin/bash
curl https://api.github.com/repos/shannty/Basic-Java-Things/commits
curl https://api.github.com/repos/shannty/Binary-Search/commits
curl https://api.github.com/repos/shannty/COSC-499/commits
curl https://api.github.com/repos/shannty/CS106B/commits
curl https://api.github.com/repos/shannty/datasciencecoursera/commits
curl https://api.github.com/repos/shannty/datasharing/commits
curl https://api.github.com/repos/shannty/go/commits
curl https://api.github.com/repos/shannty/Inheritance-Practice/commits
curl https://api.github.com/repos/shannty/MergeSort/commits
curl https://api.github.com/repos/shannty/Simple-Text-Parser/commits
curl https://api.github.com/repos/shannty/StatLearning/commits
curl https://api.github.com/repos/ewardle/cosc360-daylog/commits
curl https://api.github.com/repos/ewardle/Workshop/commits
curl https://api.github.com/repos/lamng/Drupal-Commerce/commits
curl https://api.github.com/repos/ameenshake/Ez-Buy/commits
curl https://api.github.com/repos/ameenshake/FeedMe/commits
curl https://api.github.com/repos/ameenshake/google-homepage/commits
curl https://api.github.com/repos/ameenshake/oh-my-fish/commits
curl https://api.github.com/repos/ameenshake/OKLister-Theme/commits
curl https://api.github.com/repos/ameenshake/playground/commits
curl https://api.github.com/repos/ameenshake/ProEuler/commits
curl https://api.github.com/repos/ameenshake/Scratchpad/commits
curl https://api.github.com/repos/ameenshake/Slider/commits
curl https://api.github.com/repos/ameenshake/ubco_books/commits